name: deploy

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable coursier cache
        uses: coursier/cache-action@v6
      - name: Install scala-cli
        uses: VirtusLab/scala-cli-setup@main
      - name: Setup Github Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Build website
        run: scala-cli run Generate.scala
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ".site/"

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2